Display upload progress
LinnierGames/PicPi-iOS pull request #9
Opened 2020-12-30 03:32 UTC by LinnierGames

### What's new
- Create Navigator to setup and present the Add Photo flow
- Create AddPhotoUploadSession Vc

### What has changed
- Present the AddPhoto Vc in a Navigation Vc

2020-12-30 03:35 UTC, LinnierGames reviewed
Self-reviewed

2020-12-30 03:44 UTC, LinnierGames commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display a spinner while images are sending](https://trello.com/c/hf5wS1na/69-display-a-spinner-while-images-are-sending)

2020-12-30 23:21 UTC, RawiSoft requested changes

2020-12-30 23:21 UTC, RawiSoft commented on PicPi/AddPhotoUploadSessionViewController.swift
> +    setupDoneButton()
It's a little bit confusing
SetupDoneButton , the button is searchButton and the button title is Cancel , if you don't mind fix that :)

2020-12-31 18:23 UTC, LinnierGames commented on PicPi/AddPhotoUploadSessionViewController.swift
> +    setupDoneButton()
Oops, that's wha happens when I copy and paste code, fixed

2020-12-31 18:50 UTC, merged